steps:

- id: "Rodando Docker Compose"
  name: "gcr.io/$PROJECT_ID/docker-compose:1.25.5"
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d' ]

- id: "Rodando Docker PS"
  name: "gcr.io/cloud-builders/docker"
  args: ['ps']
  
- id : 'Rodando phpComposer'
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'composer', 'install', '-d','/var/www/laravel']

- id: 'Copiand .env'
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'cp', '/var/www/laravel/.env.example', '/var/www/laravel/.env']

- id: 'Rodando key:generate'
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'php', '/var/www/laravel/artisan', 'key:generate']

- id: 'Rodando migrations'
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'php', '/var/www/laravel/artisan', 'migrate']

- id: 'Rodando Php-unit'
  name: "gcr.io/cloud-builders/docker"
  args: ['exec', '-t', 'app', 'php', '/var/www/laravel/vendor/bin/phpunit', '-c', '/var/www/laravel/phpunit.xml']